### ISSUE TITLE
vgszero-empty-project で floating point exception

### ISSUE THREAD

**Issue by suzukiplan** [suzukiplan/vgszero#53]
vgszero-empty-project の vgszero を 1.11.0 にアップデートしてビルドしたところ、デフォルトのサンプルプロジェクトを起動した時に Floating point exception でクラッシュする

```
../vgszero/src/sdl2/vgs0 game.pkg
2024.06.22 17:33:22 Booting VGS0 for SDL2.
2024.06.22 17:33:22 SDL version: 2.0.20
2024.06.22 17:33:22 Loading game.pkg
- game.rom size: 49152
- bgm.dat size: 2245
- se.dat size: 62762
2024.06.22 17:33:22 Initializing VGS0
2024.06.22 17:33:22 Initializing SDL
2024.06.22 17:33:22 Initializing AudioDriver
2024.06.22 17:33:22 - obtained.freq = 44100
2024.06.22 17:33:22 - obtained.format = 8010
2024.06.22 17:33:22 - obtained.channels = 1
2024.06.22 17:33:22 - obtained.samples = 735
2024.06.22 17:33:22 create SDL window
2024.06.22 17:33:22 Get SDL window surface
2024.06.22 17:33:22 PixelFormat: 32 bits (4 bytes)
2024.06.22 17:33:22 Rmask: 00FF0000
2024.06.22 17:33:22 Gmask: 0000FF00
2024.06.22 17:33:22 Bmask: 000000FF
2024.06.22 17:33:22 Amask: 00000000
2024.06.22 17:33:22 Start main loop...
make[1]: *** [Makefile:30: all] Floating point exception (core dumped)
make[1]: Leaving directory '/home/suzukiplan/dev/vgszero-empty-project/src'
make: *** [Makefile:4: all] Error 2
```

**Comment by suzukiplan** [comment]
crushed at NSFPlayer::Reset

```
Thread 1 "vgs0" received signal SIGFPE, Arithmetic exception.
0x0000555555583e56 in NSFPlayer::Reset() ()
(gdb) bt
#0  0x0000555555583e56 in NSFPlayer::Reset() ()
#1  0x0000555555568d87 in Z80::OUT_N_A(Z80*) ()
#2  0x0000555555561fcd in main ()
```

**Comment by suzukiplan** [comment]
VGSのBGM形式がNSF形式と誤判定されているかも。
